[package]
name = "libxdp-sys"
version = "1.5.3+1.5.3"
edition = "2021"
description = "Rust bindings for libxdp"
repository = "https://github.com/hi-glenn/libxdp-sys"
homepage = "https://github.com/hi-glenn/libxdp-sys.git"
keywords = ["libxdp", "xdp"]
license = "LGPL-2.1 OR BSD-2-Clause"
build = "build.rs"
links = "libxdp"

[build-dependencies]
bindgen = "0.72.0"
